### PR TITLE
Fix bug related to an issue with loading of schedule data from file

### PR DESCRIPTION
**Pull request by alanlowzies**
This PR contains a bug fix that resolves an issue where the plans cannot be read from `schedule.txt` when the app launches.

Upon analysis, it is discovered that in the `FileManager#addFileScheduleToList(...)` method, `PlanList#createAndAddPlan(...)` is invoked with parameters `<day number> <plan name>`. However, the correct parameter to use is `<day number> <index number of plan name>`. This index number is the positioning of the plan as stored in the `plansDisplayList` in `PlanList.java`.

As a result, the following changes/fixes have been implemented:
- [`PlanList.java`] Created a new method to retrieve the index number of a specified plan name (based on the plan's positioning in the `plansDisplayList` ArrayList.
- [`FileManager#addFileScheduleToList(...)`] Instead of calling `PlanList#createAndAddPlan(...)` with plan name as part of the argument, the index number of the plan will be used instead.
- [`FileManager.java`] As this class now requires the instance of `PlanList`, its constructor will now take in one parameter, which is the instance of `PlanList`.
- Other places in the application code, as well as test cases, have been updated to match the new signature of the `FileManager` class constructor.

### CODE REVIEW

**Review by a1021492980 — APPROVED** [review]
Thank you for fixing it in real time

**Comment by alanlowzies** [comment]
> Thank you for fixing it in real time
Just felt bad if I didn't do it asap :)

**Review by TianaiYan — APPROVED** [review]
Thank you for the quick fix.

**Review by emilysim00 — APPROVED** [review]
Looks great. Thanks for fixing the error!

**Pull request merged**
