### PR TITLE
Add List Plan

### PR DESCRIPTION
**Pull request by Musfirahe0556596**
List all plan names in a plan list.

### CODE REVIEW

**Review by TianaiYan — APPROVED** [review]
Looks great!. Thank you for your quick implementation of list plan function.

**Review by alanlowzies — APPROVED** [review]
Looks alright. Thank you

**Review by a1021492980 — APPROVED** [review]
Good implementation!

**Comment by Musfirahe0556596** [comment]
This PR also addressed #81

**Pull request merged**
